name: car225
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Architecture & State Management ---
  flutter_riverpod: ^2.4.9
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.9
  provider: ^6.1.1
  local_auth: ^2.1.6
  flutter_local_notifications: ^18.0.1

  # --- Navigation & Réseau ---
  go_router: ^13.1.0
  dio: ^5.9.1
  connectivity_plus: ^5.0.2
  curved_navigation_bar: ^1.0.3

  # --- UI & Animations ---
  flutter_animate: ^4.5.0
  flutter_svg: ^2.2.3
  google_fonts: ^6.1.0
  gap: ^3.0.0

  # --- Stockage Local ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.4

  # --- Firebase ---
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1

  # --- Utilitaires ---
  intl: ^0.20.2
  equatable: ^2.0.5
  fpdart: ^1.1.0
  dartz: ^0.10.1
  uuid: ^4.4.0
  image_picker: ^1.0.7
  device_info_plus: ^12.3.0
  io: ^1.0.5

  # --- Scanneur & QR Code ---
  mobile_scanner: ^7.1.4
  qr_flutter: ^4.1.0

  # --- Impression & PDF ---
  printing: ^5.13.4
  pdf: ^3.11.1

  # --- Gestion de fichiers ---
  path_provider: ^2.1.2
  open_filex: ^4.3.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icone.jpg"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/icons/icone.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/
    - assets/icons/
